// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimesheetManagement.Data.Contexts;

#nullable disable

namespace TimesheetManagement.Data.Migrations
{
    [DbContext(typeof(TimesheetManagementContext))]
    [Migration("20220530085419_BaseTimesheetEntities")]
    partial class BaseTimesheetEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.Timesheet.TimesheetDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DayType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TimesheetDays");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.Timesheet.TimesheetTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimesheetDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetDayId");

                    b.ToTable("TimesheetTimes");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.Timesheet.TimesheetTime", b =>
                {
                    b.HasOne("TimesheetManagement.Domain.Entities.Timesheet.TimesheetDay", "TimesheetDay")
                        .WithMany("TimesheetTimes")
                        .HasForeignKey("TimesheetDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimesheetDay");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.Timesheet.TimesheetDay", b =>
                {
                    b.Navigation("TimesheetTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
